#!/usr/bin/env python3
"""Generate the diagnostic inpaint dataset with Stable Diffusion 1.5 inpainting.

For each real image and its mask, the masked region is regenerated by the SD-1.5
inpainting model and composited back (with a blurred mask boundary) onto the
original. The result is an image where real and AI-generated pixels coexist with
a known spatial boundary -- exactly what DEAR's RAD dissection needs.

Multi-GPU: images are split across ``--num_gpus`` worker processes.

Example:
    CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python scripts/inpaint_data_gen/gen_inpaint_data.py \\
        --num_gpus 8 \\
        --input_folder data/train/real/lsun \\
        --mask_folder data/train/fake/lsun_inpaint_mask \\
        --output_folder data/train/fake/lsun_inpaint_sd
"""

import os
import argparse

import numpy as np
from PIL import Image
from tqdm import tqdm

import torch
import torch.multiprocessing as mp
from diffusers import AutoPipelineForInpainting


def process_worker(gpu_id, image_list, args):
    """Inpaint the assigned images on a single GPU."""
    device = f"cuda:{gpu_id}"
    torch.cuda.set_device(gpu_id)

    pipeline = AutoPipelineForInpainting.from_pretrained(
        'runwayml/stable-diffusion-inpainting',
        torch_dtype=torch.float16,
        variant="fp16",
    )
    pipeline.to(device)

    pbar = tqdm(total=len(image_list), desc=f"GPU {gpu_id}", position=gpu_id)
    for image_path in image_list:
        stem = os.path.basename(image_path).split('.')[0]
        mask_path = os.path.join(args.mask_folder, f"{stem}_mask.png")

        init_image = Image.open(image_path).convert("RGB")
        mask_image = Image.open(mask_path).convert("L")
        orig_w, orig_h = init_image.size

        # Inpaint at 512x512.
        init_512 = init_image.resize((512, 512), Image.BICUBIC)
        mask_512 = mask_image.resize((512, 512), Image.NEAREST)
        mask_512_blur = pipeline.mask_processor.blur(mask_512, blur_factor=33)

        result_512 = pipeline(prompt="", image=init_512, mask_image=mask_512_blur).images[0]

        # Composite generated region over the original (blurred boundary).
        orig_np = np.array(init_512).astype(np.float32)
        res_np = np.array(result_512).astype(np.float32)
        mask_np = np.array(mask_512_blur).astype(np.float32)[..., None] / 255.0
        final_np = res_np * mask_np + orig_np * (1 - mask_np)

        final_512 = Image.fromarray(final_np.astype(np.uint8))
        final_image = final_512.resize((orig_w, orig_h), Image.BICUBIC)
        final_image.save(os.path.join(args.output_folder, f"{stem}_inpaint.png"))

        pbar.update(1)
    pbar.close()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_folder", type=str, default="data/train/real/lsun")
    parser.add_argument("--mask_folder", type=str, default="data/train/fake/lsun_inpaint_mask")
    parser.add_argument("--output_folder", type=str, default="data/train/fake/lsun_inpaint_sd")
    parser.add_argument("--num_gpus", type=int, default=1)
    args = parser.parse_args()

    os.makedirs(args.output_folder, exist_ok=True)

    imgs = [
        os.path.join(args.input_folder, f)
        for f in os.listdir(args.input_folder)
        if f.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp'))
    ]
    total = len(imgs)
    print(f"Total images: {total}")
    print(f"Using {args.num_gpus} GPUs")

    # Split images across GPUs.
    images_per_gpu = total // args.num_gpus
    assignments = []
    for gpu_id in range(args.num_gpus):
        start = gpu_id * images_per_gpu
        end = (gpu_id + 1) * images_per_gpu if gpu_id < args.num_gpus - 1 else total
        assignments.append(imgs[start:end])

    mp.set_start_method("spawn", force=True)
    processes = []
    for gpu_id in range(args.num_gpus):
        p = mp.Process(target=process_worker, args=(gpu_id, assignments[gpu_id], args))
        p.start()
        processes.append(p)
    for p in processes:
        p.join()

    print("\n================ DONE ================")


if __name__ == "__main__":
    main()
