defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  run:
    dir: .
  output_subdir: null

pipeline_name: corvi
save_path: results/${pipeline_name}
mode: train  # train, inference
seed: 0
device: cuda

# wandb (optional logging)
use_wandb: false
wandb_group: debug
wandb_name: ${pipeline_name}

# dataset (real LSUN/COCO vs. LDM fakes)
data_root: ./data
train_real_types: ['coco', 'lsun']
train_fake_types: ['ldm']
val_real_types: ['coco', 'lsun']
val_fake_types: ['ldm']

# dataloader
batch_size: 1024
num_workers: 16

# transform / augmentation
transform:
  crop_size: 96
  resize_size: 256
  resize_ratio: 0.75
  norm_type: resnet
  resize_prob: 0.2
  jitter_prob: 0.8
  colordist_prob: 0.2
  cutout_prob: 0.2
  noise_prob: 0.2
  blur_prob: 0.5
  cmp_prob: 0.5
  rot90_prob: 1.0
  no_flip: false
  blur_sig: [0.0, 3.0]
  cmp_method: ['cv2', 'pil']
  cmp_qual: [30, 100]

# training
num_epochs: 1000
lr: 0.0001
beta1: 0.9
weight_decay: 0.0
earlystop_patience: 5
earlystop_delta: 0.001
save_every: 1

# inference
test_dirname: test
test_real_types: ['redcaps']
test_fake_types: ['sd','Midjourney','kandinsky','playground','pixelart','lcm','flux','wuerstchen','amused','Chameleon','loki','WildRF']
num_test_samples: null
webp_quality: null  # 0-100
resize_ratio: null  # 0-1
